# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_core.ipynb",
         "handover_grasping_dataset": "Dataloader.ipynb",
         "image_net_mean": "Dataloader.ipynb",
         "image_net_std": "Dataloader.ipynb",
         "HANet": "model.ipynb",
         "get_grasp_line": "utils.ipynb",
         "get_affordancemap": "utils.ipynb",
         "get_model": "utils.ipynb"}

modules = ["core.py",
           "Dataloader.py",
           "model.py",
           "utils.py"]

doc_url = "https://ARG-NCTU.github.io/handover_grasping/"

git_url = "https://github.com/ARG-NCTU/handover_grasping/tree/{branch}/"

def custom_doc_links(name): return None
