# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"handover_grasping_dataset": "00_Datavisualizer.ipynb",
         "rosenberger_dataloader": "00_Datavisualizer.ipynb",
         "parallel_jaw_based_grasping_dataset": "00_Datavisualizer.ipynb",
         "Card": "00_core.ipynb",
         "HANet": "01_grasping_estimation.ipynb",
         "HANet_depth": "01_grasping_estimation.ipynb",
         "GGCNN": "01_grasping_estimation.ipynb",
         "ConvNet": "01_grasping_estimation.ipynb",
         "DopeNetwork": "01_grasping_estimation.ipynb",
         "Draw": "01_grasping_estimation.ipynb",
         "DopeNode": "01_grasping_estimation.ipynb",
         "Image_table": "02_utils.ipynb",
         "get_grasp_line": "02_utils.ipynb",
         "get_affordancemap": "02_utils.ipynb",
         "get_model": "02_utils.ipynb",
         "get_pcd_right": "02_utils.ipynb",
         "get_pcd_left": "02_utils.ipynb",
         "get_view": "02_utils.ipynb",
         "vis": "02_utils.ipynb",
         "bwareaopen": "03_getheightmap.ipynb",
         "bg_subtraction": "03_getheightmap.ipynb",
         "project_depth2camera": "03_getheightmap.ipynb",
         "points2world": "03_getheightmap.ipynb",
         "getgridmapping": "03_getheightmap.ipynb",
         "getheightmapColor": "03_getheightmap.ipynb",
         "heightmapwithbgsubtraction": "03_getheightmap.ipynb",
         "FixMissingDepth2camera": "03_getheightmap.ipynb",
         "getMissingdepthheightmap": "03_getheightmap.ipynb",
         "denoiseheightmap": "03_getheightmap.ipynb",
         "grid_x": "03_getheightmap.ipynb",
         "grid_y": "03_getheightmap.ipynb"}

modules = ["Datavisualizer.py",
           "core.py",
           "model.py",
           "utils.py",
           "getheightmap.py"]

doc_url = "https://ARG-NCTU.github.io/handover_grasping/"

git_url = "https://github.com/ARG-NCTU/handover_grasping/tree/{branch}/"

def custom_doc_links(name): return None
