# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ARG-NCTU.github.io/handover_grasping/"

git_url = "https://github.com/ARG-NCTU/handover_grasping/tree/{branch}/"

def custom_doc_links(name): return None
